# -*- coding: utf-8 -*-
"""EVP Correlation btw MY and ER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWnXr1ZwhJHuflTLg8Qm6fjtqpFTT2og

#Analysis of Electric Vehicles Population correlation between Model Year and Electric Range.
##Here we try to create visualization for analysis of electric vehicle population relation between model year and electric range.
"""

# Importing required libereary
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#loading the data
dataset = pd.read_csv(r"C:\Users\tabs2\Downloads\Programming Assessment\Electric-Vehicle-Population-\Electric_Vehicle_Population_Data.csv")
dataset

#Plot figure size
plt.figure(figsize=(12,6))

# Plotting a scattered grapgh
sns.scatterplot(data = dataset, x= 'Model Year', y = 'Electric Range', alpha =0.6, color = 'purple')
plt.title('Correlation Between Model Year and Electric Range')
plt.xlabel('Model Year')
plt.ylabel('Electric Range (miles)')
plt.grid(True)
plt.tight_layout()


# Save the plot in a png file
plt.savefig('electric_vehicles_types.png')

#Display the plot
plt.show()