# -*- coding: utf-8 -*-
"""Electric Vehicle Types.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uritKIvpbq4Ilc6YEOwdqmKp8-ioysHA

#Electric Vehicle Type
## Here we will try to visualize the data and find the various electric vehicle types in the dataset
"""

#Importing required liberaries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Loading the dataset
vehicleType = pd.read_csv(r"C:\Users\tabs2\Downloads\Programming Assessment\Electric-Vehicle-Population-\Electric_Vehicle_Population_Data.csv")
# Printing and analyzing the data
vehicleType

#Counting the no. of each electric vehicles
evTypeCount = vehicleType['Electric Vehicle Type'].value_counts()
#print the counts
evTypeCount

#Plot figure size
plt.figure(figsize =(15,6))
# ploting a bar
sns.barplot(x=evTypeCount.index, y = evTypeCount.values)
plt.title('Distribution of Electric Vehicles Types')
plt.ylabel('Number of Vehicles')
plt.xlabel('Electric Vehicles')
plt.tight_layout()

# Save the plot in a png file
plt.savefig('electric_vehicles_types.png')

#Display the plot
plt.show()