# -*- coding: utf-8 -*-
"""EV Distribution by county in WS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FqerEE53a79ppysx6nozgUevKyvaRHaY

#Electric Vehicle Distribution by County in Washington State.
## We are trying to analyse the Electric Vehicle Distribution by County in Washington State.
"""

#pip install -U kaleido
#tried to install Kaleido to save the map in directory but getting error even after installation

# Importing required libereary
import pandas as pd
import plotly.express as px

#loading the data
dataset = pd.read_csv(r"C:\Users\tabs2\Downloads\Programming Assessment\data\Electric-Vehicle-Population-\Electric_Vehicle_Population_Data.csv")
dataset

#getting the values of county

stateCount = dataset['State'].value_counts().reset_index()
stateCountColumn = ['State','Number of Electric Vehicles']

#print the values
stateCount

# Save the modified dataset to a new CSV file
stateCount.to_csv('count_county.csv', index=False)

#creating a choropleth map
'''fig= px.choropleth(countyCount,
                   geojson = px.data.election_geojson(),
                   locations = 'County',
                   featureidkey='properties.name',
                   color = 'index',
                   scope = "usa",
                   labels = {'Number of Electric Vehicles':'NUmber of EVs'},
                   title = 'Number of Electric Vehicle by County in Washigton State')

fig.update_geos(fitbounds = "locations",visible = False)
tried the above the map was not comming with color difference
'''
fig= px.choropleth(stateCount,
                   locations = 'State',
                   locationmode="USA-states",
                   color = 'State',
                   scope = "usa",
                   labels = {'Number of Electric Vehicles':'Number of EVs'},
                   title = 'Number of Electric Vehicle by County in Washigton State'

)

# Save the plot as an image (e.g., PNG)
#fig.write_image('map.png')


fig.show()