# -*- coding: utf-8 -*-
"""Electric Vehicle in each county .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lzTCUz5102DCLFWueo7oW87cu79ejx40

#Electric Vehicle in each County
## We are visulatisation to get the electric vehicle in each county
"""

# Importing required libereary
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#loading the data
dataset = pd.read_csv('/content/drive/MyDrive/Electric_Vehicle_Population_Data.csv')
dataset

# To get top 5 county having more no. of electric vehicle
county = dataset['County'].value_counts().head(5)

# Save the modified dataset to a new CSV file
county.to_csv('county.csv', index=False)

plt.figure(figsize = (12,6))

sns.barplot(x=county.index, y=county.values)

plt.title('Top 5 Counties with Electric Vehicles')
plt.xlabel('County')
plt.ylabel('Number of Vehicles')
plt.xticks(rotation = 45)

# Save the plot in a png file
plt.savefig('electric_vehicle_in_county.png')

#show the plot
plt.show()